spring:
<% if (springDataEnabled && springDataRepositoryType === 'RDMS') { -%>
  flyway:
    locations: classpath:/db/migration,classpath:/db/dev
  h2:
    console:
      enabled: true
<% } -%>
  output:
    ansi:
      enabled: always
