version: '2'
services:

  # Application container
  <%- artifactId %>:
    image: <%- artifactId %>:latest
<% if (webServer) { -%>
    ports:
      - "<%- webServerPort %>:<%- webServerPort %>"
<% } -%>

network:
  <%- artifactId %>:
