pipeline{
    agent any
    stages{
        stage('Cleanup') {
            steps {
                sh '<%- manager === 'gradle' ? 'gradlew clean' : 'mvnw clean' %>'
            }
        }

        stage('Static code analysis') {
            steps {
                sh '<%- manager === 'gradle' ? 'gradlew staticCodeAnalysis' : 'mvnw site' %>'
            }
            post {
                always {
                    recordIssues aggregatingResults: true, sourceCodeEncoding: 'UTF-8', tools: [
                        checkStyle(pattern: '<%- manager === 'gradle' ? 'build/reports/checkstyle/*.xml' : 'target/checkstyle-result.xml' %>'),
                        cpd(pattern: <%- manager === 'gradle' ? 'build/reports/cpd/*.xml' : 'target/cpd.xml' %>'),
                        java(pattern: '**/*.log'),                        
                        spotBugs(pattern: <%- manager === 'gradle' ? 'build/reports/spotbugs/*.xml' : 'target/spotbugsXml.xml' %>', useRankAsPriority: true)
                    ]
                }
            }
        }

        stage('Unit testing') {
            steps {
                sh '<%- manager === 'gradle' ? 'gradlew check' : 'mvnw verify' %>'
            }
            post {
                always {
                    junit '<%- manager === 'gradle' ? 'build/test-results/test/*.xml' : 'target/surefire-reports/*.xml' %>'
                }
                success {
                    jacoco execPattern: '<%- manager === 'gradle' ? 'build/jacoco/*.exec' : 'target/*.exec' %>'
                }
            }
        }

        stage('Integration testing') {
            steps {
                sh '<%- manager === 'gradle' ? 'gradlew check' : 'mvnw verify' %>'
            }
            post {
                always {
                    junit '<%- manager === 'gradle' ? 'build/test-results/test/*.xml' : 'target/surefire-reports/*.xml' %>'                    
                }
                success {
                    jacoco execPattern: '<%- manager === 'gradle' ? 'build/jacoco/*.exec' : 'target/*.exec' %>'
                }
            }
        }

        // stage('E2E testing') {
        //     steps {
        //         sh '<%- manager === 'gradle' ? 'gradlew check' : 'mvnw verify' %>'
        //     }
        //     post {
        //         always {
        //             junit '<%- manager === 'gradle' ? 'build/test-results/test/*.xml' : 'target/surefire-reports/*.xml' %>'
        //         }
        //         success {
        //             jacoco execPattern: '<%- manager === 'gradle' ? 'build/jacoco/*.exec' : 'target/*.exec' %>'
        //         }
        //     }
        // }

        stage('Comment pull request') {
            when { changeRequest() }
            environment {
                REPOSITORY_NAME = "${env.GIT_URL.tokenize('/')[3].split('\\.')[0]}"
                REPOSITORY_OWNER = "${env.GIT_URL.tokenize('/')[2]}"
            }
            steps {
                ViolationsToGitHub([
                    gitHubUrl: env.GIT_URL,
                    repositoryName: env.REPOSITORY_NAME,
                    repositoryOwner: env.REPOSITORY_OWNER,
                    pullRequestId: env.CHANGE_ID,

                    createCommentWithAllSingleFileComments: false,
                    createSingleFileComments: true,
                    commentOnlyChangedContent: true,
                    minSeverity: 'INFO',
                    keepOldComments: false,

                    violationConfigs: [
                        [parser: 'CHECKSTYLE', reporter: 'Checkstyle', pattern: '<%- manager === 'gradle' ? 'build/reports/checkstyle/.*\\.xml' : 'target/checkstyle-result.xml' %>'],
                        [parser: 'CPD', reporter: 'CPD', pattern: '<%- manager === 'gradle' ? 'build/reports/cpd/.*\\.xml' : 'target/cpd.xml'%>'],
                        [parser: 'FINDBUGS', reporter: 'Spotbugs', pattern: '<%- manager === 'gradle' ? 'build/reports/spotbugs/.*\\.xml' : 'target/spotbugsXml.xml'%>'],
                   ]])
            }
        }
    }
}
