version: '2'
services:

  # Application container
  service:
    image: <%- projectName %>:latest
    ports:
      - "8080:<%- webserverPort %>"

<% if (springDataRepository === 'MySQL') { -%>
  # MySQL
  mysql:
    extends:
      file: docker-compose-infrastructure.yml
      service: mysql
<% } -%>
