version: '2'
services:

<% if (elasticSearchEnabled) { -%>
  # ElasticSearch
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - es-data:/usr/share/elasticsearch/data
<% } -%>
<% if (springDataEnabled && springDataRepository === 'MySQL') { -%>
  # MySQL
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - ./docker/conf/mysql-initdb:/docker-entrypoint-initdb.d:ro
<% } -%>
<% if (springDataEnabled && springDataRepository === 'Redis') { -%>
  # Redis
  redis:
    image: redis:5.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data:rw
<% } -%>

volumes:
<% if (springDataEnabled && springDataRepository === 'MySQL') { -%>
  es-data:
<% } -%>
<% if (elasticSearchEnabled) { -%>
  mysql-data:
<% } -%>
<% if (springDataEnabled && springDataRepository === 'Redis') { -%>
  redis-data:
<% } -%>

network:
  <%- projectName %>:
