version: '2'
services:

<% if (springDataEnabled && springDataRepository === 'MySQL') { -%>
  # MySQL
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - ./docker/conf/mysql-initdb:/docker-entrypoint-initdb.d:ro
<% } -%>
