management:
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
<% if (springDataEnabled && springDataRepositoryType === 'RDMS') { -%>
    db:
      enabled: true
<% } -%>
<% if (elasticSearchEnabled) { -%>
    elasticsearch:
      enabled: true
<% } -%>
<% if (springDataEnabled && springDataRepository === 'Redis') { -%>
    redis:
      enabled: true
<% } -%>
<% if (webServer) { -%>
server:
  port: ${PORT:<%- webserverPort %>}
<% } -%>

spring:
  application:
    name: <%=projectName%>
  profiles:
    active: dev
<% if (springDataEnabled) { -%>
  jpa:
    open-in-view: false
<% } -%>
