management:
  health:
    defaults:
      enabled: true
<% if (springDataEnabled && springDataRepositoryType === 'RDMS') { -%>
    db:
      enabled: true
<% } -%>

<% if (webServer) { -%>
server:
  port: ${PORT:8400}
  <% if (springDataEnabled) { -%>
spring:
  jpa:
    open-in-view: false
<% }} -%>
