management:
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
<% if (springDataEnabled && springDataRepositoryType === 'RDMS') { -%>
    db:
      enabled: true
<% } -%>

<% if (webServer) { -%>
server:
  port: ${PORT:<%- webserverPort %>}
<% } -%>
<% if (springDataEnabled) { -%>
spring:
  jpa:
    open-in-view: false
<% } -%>
